### PR TITLE
Prevent caching failed assets

### LINKED ISSUE #471: Retry engine on assets error
Hi.
I don't know if this is really a bug or is the correct implementation but I think I found a cache problem when dealing with the lazy engines.

### How to reproduce the error:
1. Visit an application with a lazy load engine (don't load it yet).
2. In developer tools **enable** the **Offline** mode in the Network panel.
3. Navigate to the lazy engine, the assets _engine.js_ and _engine-vendor.js_ must fail at this point.
4. **Disable** the **Offline** mode.
5. Try to access again to the lazy engine, at this point the engine is inaccesible because the previous errored promise is cached [router-ext.js#L206](https://github.com/ember-engines/ember-engines/blob/master/addon/-private/router-ext.js#L206).

### ¿Why I think the current cache is a bug?
When developing a mobile app the user sometimes can have troubles with its connection, maybe because the wifi is lost or there is not enought network coverage.

To fix the problem I've created a branch named *error-cache* in both [ember-engines](https://github.com/BBVAEngineering/ember-engines/tree/error-cache) and [ember-asset-loader](https://github.com/BBVAEngineering/ember-asset-loader/tree/error-cache) repos (only 2 or 3 commits).
The fix needs changes in 2 repos and I'm not sure if this changes can have side effects, thats why I opened an issue instead a pull-request.

¿What do you think?

### PR DESCRIPTION
**Pull request by josex2r**
Hi. This pull contains changes to fix [ember-engines#471](https://github.com/ember-engines/ember-engines/issues/471).

The service always stores the promise even if the asset fails loading. Removing the promise and the DOM node allows to retry the load.

### CODE REVIEW

File: addon/loaders/css.js [hunk 1]
```diff
@@ -20,7 +20,12 @@ export default nodeLoader(function css(uri) {
     }
 
     // Try using the default onload/onerror handlers...
-    const link = createLoadElement('link', resolve, reject);
+    const link = createLoadElement('link', resolve, function() {
+      if (this.parentNode) {
+        this.parentNode.removeChild(this);
```
Comment (rwjblue) [inline addon/loaders/css.js]: Is `this` guaranteed here? Does `createLoadElement` call it purposefully bound?

File: addon/loaders/css.js [hunk 2]
```diff
@@ -20,7 +20,12 @@ export default nodeLoader(function css(uri) {
...
+      }
+      reject(...arguments);
```
Comment (rwjblue) [inline addon/loaders/css.js]: I think we can only reject with a single value (its part of the A+ Promise spec I believe), so you can probably just do:

```js
function(error) {
  if (this.parentNode) {
    this.parentNode.removeChild(this);
  }
  reject(error);
}
```

File: addon/loaders/js.js [hunk 3]
```diff
@@ -15,7 +15,12 @@ export default nodeLoader(function js(uri) {
       return resolve();
     }
 
-    const script = createLoadElement('script', resolve, reject);
+    const script = createLoadElement('script', resolve, function() {
+      if (this.parentNode) {
+        this.parentNode.removeChild(this);
+      }
+      reject(...arguments);
```
Comment (rwjblue) [inline addon/loaders/js.js]: Same as above (`reject(error)`)

**Review by rwjblue — COMMENTED** [review]
A few minor points here to address, but generally looks good.

Adding @trentmwillis for review also...

File: addon/loaders/css.js (hunk 1 above)
Comment (josex2r) [reply addon/loaders/css.js]: I'm not 100% sure :S 
Maybe its better to use the first arg (`event.target`) instead of `this`.

Comment (trentmwillis) [reply addon/loaders/css.js]: It sets the `resolve`/`reject` functions to the `onload`/`onerror` attributes, so it will have the element context. Tests would fail if that doesn't work, so this seems fine to me unless we want to be a bit more specific about what `this` is.

File: tests/unit/services/asset-loader-test.js [hunk 4]
```diff
@@ -127,6 +127,42 @@ test('loadBundle() - a rejection allows retrying the load', function(assert) {
...
+        assets: [
+          { type: 'fail', uri: 'someuri' }
+        ]
+      }
+    }
+  });
+
+  service.defineLoader('fail', () => RSVP.reject('rejected'));
+
+
```
Comment (trentmwillis) [inline tests/unit/services/asset-loader-test.js]: Nit: extra line

**Review by trentmwillis — COMMENTED** [review]
+1 to @rwjblue's other comments, but overall looking good. Thanks for working on this!

**Comment by rwjblue** [comment]
Thank you again!

**Comment by rwjblue** [comment]
Released as v0.3.1.

**Comment by josex2r** [comment]
You're welcome :)
